### ISSUE TITLE
BUG report

### ISSUE THREAD

**Issue by atlasbioinfo** [Halvee/SNPfoldPy#1]
I wanna evaluate the RNA structural differences when several SNPs were simultaneously altered.

```bash
SNPfold_commandline.py -A ATTTCGAGCAAGCACCGCCGCCGACGCATCTCGAGTAGTTTCCAGCTCGCCGGAGGAGGAGAAAG G8A,C22T,G23C,A24C,C46T,G56A
```

The output:
```bash
MUT     CC_BPPROB       CC_BPPROB_PVAL  CC_SHANNON      CC_SHANNON_PVAL
Traceback (most recent call last):
  File "/home/atlas/anaconda3/envs/py2/bin/SNPfold_commandline.py", line 490, in <module>
    SNPfold_commandline(sys.argv)
  File "/home/atlas/anaconda3/envs/py2/bin/SNPfold_commandline.py", line 436, in SNPfold_commandline
    outputLine.append(str(AllFoldingsObj.cchash[subtype][mut]))
KeyError: 'G8A,C22U,G23C,A24C,C46U,G56A'
```
The web version works fine:
http://ribosnitch-compute.bio.unc.edu/snpfold/SNPfold.html

**Comment by Halvee** [comment]
Hi, the accurate p-value calculation method implemented here that was originally described in PMID 20808897 is designed for single nucleotide mutants only. Extending this method to instances like you've listed (6 point mutations in the mutant sequence) would involve sampling structural change of all possible mutants of the wildtype sequence that involve 6 point mutations total, which is beyond the scope of this software. I've updated the code here to reflect this more formally. The same caveats would apply to results from the server, though I don't believe there are any plans to update the code there in a similar manner.

**Comment by atlasbioinfo** [comment]
> Hi, the accurate p-value calculation method implemented here that was originally described in PMID 20808897 is designed for single nucleotide mutants only. Extending this method to instances like you've listed (6 point mutations in the mutant sequence) would involve sampling structural change of all possible mutants of the wildtype sequence that involve 6 point mutations total, which is beyond the scope of this software. I've updated the code here to reflect this more formally. The same caveats would apply to results from the server, though I don't believe there are any plans to update the code there in a similar manner.

Many thanks for your reply.
